#!/bin/bash
set -ouex pipefail

# Repository setup
curl -fsSL https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc \
    | gpg --dearmor | dd of=/etc/apt/trusted.gpg.d/linux-surface.gpg
echo "deb [arch=amd64] https://pkg.surfacelinux.com/debian release main" \
	| tee /etc/apt/sources.list.d/linux-surface.list

# Initial update
apt-get update -y

# Install Surface Bits
apt-get purge -y \
	"linux-image-$(dpkg --print-architecture)"
rm -rf /usr/lib/modules/*
apt-get install -y \
	linux-image-surface \
	linux-headers-surface \
	libwacom-surface \
	iptsd

apt list --installed > /usr/share/snow/snowfield.packages.txt

# Update os-release info
echo 'IMAGE_ID="Snowfield"' >> /usr/lib/os-release

# Update build information in os-release
sed -i "s/^BUILD_ID=.*/BUILD_ID=\"$BUILD_ID\"/" /usr/lib/os-release
